language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mterrano1/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mterrano1/docker-react npm run test


#script:
  #- docker run -e CI=true USERNAME/docker-react npm run test